repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix]

      - id: ruff-format

  - repo: local
    hooks:
      - id: task-test
        name: task test
        entry: poetry run task test
        language: system
        pass_filenames: false
        always_run: true